### PR TITLE
Support Dry Run & No Github Issues Interaction if repo doesn't use issues

### PR DESCRIPTION
**Pull request by brianhuang822**
Support Dry Run & No Github Issues Interaction if repo doesn't use issue

### CODE REVIEW

**Comment by crs-k** [comment]
Thanks for putting this together! I should have time to review tomorrow morning.

**Comment by hxii** [comment]
@crs-k Hey! What are the chances this might be approved this week?

**Comment by PavelKuprinTDH** [comment]
@crs-k Hey Chris!
Hope you are doing well!
Take a look, plz.
We all need DRY RUN support)))

**Comment by cayla** [comment]
@PavelKuprinTDH Please don't nag maintainers.  Someone already asked for an update just a few days earlier.  This is all volunteer effort.

**Comment by PavelKuprinTDH** [comment]
> @PavelKuprinTDH Please don't nag maintainers.  Someone already asked for an update just a few days earlier.  This is all volunteer effort.  

Calm down. I'm not forcing the maintainer. It was just a polite ask.

**Review by crs-k — APPROVED** [review]

**Pull request merged**
